### ISSUE TITLE
Unit test failure on Mac arm64

### ISSUE THREAD

**Issue by hpages** [LTLA/metapod#1]
Similar to https://github.com/LTLA/BiocNeighbors/issues/21 and https://github.com/LTLA/csaw/issues/21.

Unit test failures ("Objects equal but not identical") on Mac arm64: https://bioconductor.org/checkResults/3.18/bioc-mac-arm64-LATEST/metapod/kjohnson1-checksrc.html

No Mac arm64 binary in BioC 3.18: https://bioconductor.org/packages/3.18/metapod

The missing **metapod** binary is blocking propagation of at least 26 Bioconductor Mac arm64 binaries in BioC 3.18!

Thanks,
H.

**Comment by LTLA** [comment]
Should be fixed in 1.11.1 and 1.10.1.

**Comment by hpages** [comment]
Thanks!
